// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConfirmHostKey(arg1:string,arg2:boolean):Promise<void>;

export function Connect(arg1:main.ConnectionOptions):Promise<string>;

export function Disconnect(arg1:string):Promise<void>;

export function DisconnectAll():Promise<void>;

export function LoadSettings():Promise<main.TerminalSettings>;

export function Resize(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SaveSettings(arg1:main.TerminalSettings):Promise<void>;

export function SelectPrivateKey():Promise<string>;

export function SendInput(arg1:string,arg2:string):Promise<void>;
